// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHr1LoM2HwpV6KWgj4Nc_OrpY4ERfjIlw',
    appId: '1:214736634664:web:5c2cf70c78c5703b31c61d',
    messagingSenderId: '214736634664',
    projectId: 'app4hr-a0867',
    authDomain: 'app4hr-a0867.firebaseapp.com',
    storageBucket: 'app4hr-a0867.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKRtFtrX22oZsunyMBP1jhGmPDjwhJts',
    appId: '1:214736634664:android:9c1d98d70693ef4c31c61d',
    messagingSenderId: '214736634664',
    projectId: 'app4hr-a0867',
    storageBucket: 'app4hr-a0867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsU-qfk38mddIWoKpWZojPRFSl0zL-QcU',
    appId: '1:214736634664:ios:0eda73e9e01921f031c61d',
    messagingSenderId: '214736634664',
    projectId: 'app4hr-a0867',
    storageBucket: 'app4hr-a0867.appspot.com',
    iosClientId: '214736634664-feg0hgk3e6diicvnippfl9lem0n9pc8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.app4hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsU-qfk38mddIWoKpWZojPRFSl0zL-QcU',
    appId: '1:214736634664:ios:0eda73e9e01921f031c61d',
    messagingSenderId: '214736634664',
    projectId: 'app4hr-a0867',
    storageBucket: 'app4hr-a0867.appspot.com',
    iosClientId: '214736634664-feg0hgk3e6diicvnippfl9lem0n9pc8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.app4hr',
  );
}
